### PR TITLE
Bugfix: Make core 500 error handler work for Guests (fixes #3002)

### LINKED ISSUE #3002: bork is borked when not logged in.
There is a static route /bork which seems to exist to trigger an exception which is then caught and passed to Bugsnag.

http://exercism.io/bork

This seems to work correctly when you are logged in to Exercism, but when you are not it results in a long textual stacktrace.

```
Puma caught this error: undefined method `username' for #<Guest:0x007fea625d0d78> (NoMethodError)
/app/app/routes/core.rb:27:in `block in <class:Core>'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `[]'
<another 50 or so lines omitted>
```

The error handler should be fixed to handle a `nil` current_user

### PR DESCRIPTION
**Pull request by Insti**
The error handler was erroring if the user was not logged in because the Guest class did not have a `username` method.

Add `username` method to Guest.
100% unit test coverage of Guest

Also, `BUILD_ID` is now availiable as a constant so use that instead of the environment variable.

### CODE REVIEW

**Comment by Insti** [comment]
We should\* see an increase in activity on Bugsnag due to this, since guest errors were being dropped previously.

\* I hope we won't.

File: test/exercism/guest_test.rb [hunk 1]
```diff
@@ -1,8 +1,51 @@
 require_relative '../test_helper'
+require_relative '../active_record_helper'
```
Comment (Insti) [inline test/exercism/guest_test.rb]: I really don't like that this test is dependent on Activerecord

File: test/exercism/guest_test.rb [hunk 2]
```diff
@@ -1,8 +1,51 @@
...
+  end
+
+  def test_fetched?
+    subject = Guest.new
+    refute subject.fetched?
+  end
+
+  def test_exercises
+    subject = Guest.new
+    expected = UserExercise.where('1=2')
```
Comment (Insti) [inline test/exercism/guest_test.rb]: The dependency is caused by UserExercise.

File: test/exercism/guest_test.rb (hunk 1 above)
Comment (Insti) [inline test/exercism/guest_test.rb]: I guess it's not so surprising since Guest is basically a NullObject version of User which is an ActiveRecord object.

File: test/exercism/guest_test.rb (hunk 2 above)
Comment (Insti) [inline test/exercism/guest_test.rb]: [Here's a version that fakes out UserExercise](https://github.com/Insti/exercism.io/blob/69390b699711091ace5a135c93f4f1588debbaf7/test/exercism/guest_test.rb) I'm not sure if that's an improvement though.

File: test/exercism/guest_test.rb (hunk 1 above)
Comment (kytrinyx) [inline test/exercism/guest_test.rb]: No, it's not because of User, it's because of the UserExercise at the bottom.

File: test/exercism/guest_test.rb (hunk 2 above)
Comment (kytrinyx) [inline test/exercism/guest_test.rb]: I don't recall the history of this. But why is Guest even doing a query? We know it's going to be an empty array.

File: test/exercism/guest_test.rb (hunk 1 above)
Comment (Insti) [inline test/exercism/guest_test.rb]: Well not *directly* but it's only using UserExercise because that is what User.exercise returns.

Comment (kytrinyx) [inline test/exercism/guest_test.rb]: ah, right. Hm. I wish we could untangle it in the case of the guest.

File: test/exercism/guest_test.rb (hunk 2 above)
Comment (Insti) [inline test/exercism/guest_test.rb]: You'd think so wouldn't you, but User.exercises returns an Active(something) object rather than a simple array.

**Comment by Insti** [comment]
We should merge this, my musings about testing are completely tangential at this point.

**Comment by kytrinyx** [comment]
Yeah, agreed. Thanks for taking the time to both do the work and muse on testing!

**Comment by Insti** [comment]
Refactoring User and Guest is on my ideas list.

**Comment by Insti** [comment]
If you put it live I can test the Bugsnap bits work again.

**Comment by kytrinyx** [comment]
Sweet, yeah—I was going to deploy earlier today and then ended up in back to back meetings. Deploying now.

**Comment by kytrinyx** [comment]
And deployed.

**Comment by Insti** [comment]
The error page isn't failing any more, but Bugsnag still doesn't seem to be being notified.
I'll investigate some more.

**Comment by Insti** [comment]
@kytrinyx I'm not seeing the expected Bugsnag notifications from /bork in production.
(They worked from my development machine.)

Is the API key environment variable set? (I expect it is, since the Github connection notifications worked recently.)
Are there any configuration files that might be setting 'auto_notify' to false? (it defaults to true.)

Any other ideas?

**Comment by kytrinyx** [comment]
> Is the API key environment variable set?

Yes, it's set.

> Are there any configuration files that might be setting 'auto_notify' to false?

No, not that I know of.

> Any other ideas?

Did you check in bugsnag itself, or were you expecting an email?

**Comment by Insti** [comment]
I checked in Bugsnag.

I triggered one from my Dev machine which worked as expected.

**Comment by kytrinyx** [comment]
That's so odd. It used to work. I wonder at what point I broke it.

**Comment by Insti** [comment]
After you deploy again I can test some more.

**Comment by kytrinyx** [comment]
I've deployed again.

**Comment by Insti** [comment]
Gitter shows: 9e471c8 as deployed but http://exercism.io/version is still showing 6a5e056 (the previous version)

**Comment by Insti** [comment]
Does your deploy stop and start the server?

**Comment by kytrinyx** [comment]
Yes, it does. I've had some environment trouble locally in the past week (I know the cause, not the solution—yet), so that might have affected some hooks and things.
