### PR TITLE
Fix help request display on team stream. (fixes #3018)

### LINKED ISSUE #3018: Broken avatar and all tagged with "Help Requested" on Team view.
Showing all flagged with help and links instead of avatars

On any team view that I see, it looks similar.

### PR DESCRIPTION
**Pull request by Insti**
`help_requested` also needs to be implemented in track_stream due to the code duplication between track_stream and team_stream.

### CODE REVIEW

**Comment by Insti** [comment]
Note that these fixes, (and the underlying bug) currently have no tests.
I intend to add automatic test coverage, but wanted to make the fix available before the tests were completed in case the bug was considered urgent.

**Comment by Insti** [comment]
Fixes #3018

File: lib/exercism/stream_exercise.rb [hunk 1]
```diff
@@ -2,13 +2,19 @@ module Stream
...
     def comment_count
       @comment_count || 0
     end
 
-    def at
-      @at ||= last_activity_at.to_datetime
-    end
+    # Unused? 20160801 1129
+    # def at
+    #  @at ||= last_activity_at.to_datetime
```
Comment (Insti) [inline lib/exercism/stream_exercise.rb]: No this is used. (in a view, and is not tested at all.)
:exclamation: do not merge :exclamation:

File: test/exercism/stream_exercise_test.rb [hunk 2]
```diff
@@ -0,0 +1,52 @@
+require_relative '../test_helper'
+require 'exercism'
+
+class StreamExerciseTest < Minitest::Test
+
+  # Also not constructed :/
```
Comment (kytrinyx) [inline test/exercism/stream_exercise_test.rb]: What's the context of this comment?

File: test/exercism/stream_exercise_test.rb [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+
+  def test_at
+    date = '2016-08-01'
+    args = [:id, :uuid, :problem, :last_activity, date, :iteration_count, :last_activity_at, :help_requested, :avatar_url]
+    exercise = Stream::Exercise.new(*args)
+    expected = date.to_datetime
+    assert_equal expected, exercise.at
+  end
+
+  # It's not possible to construct a viewed exercise.
```
Comment (kytrinyx) [inline test/exercism/stream_exercise_test.rb]: I'm not sure what you mean by viewed exercise. An exercise is only viewed in the context of a viewer.

File: test/exercism/stream_exercise_test.rb [hunk 4]
```diff
@@ -0,0 +1,52 @@
...
+  def test_viewed!
+    # See test_unread?
+  end
+
+  # It's not possible to construct an viewed exercise.
```
Comment (kytrinyx) [inline test/exercism/stream_exercise_test.rb]: minor typo: `s/an/a/`

File: test/exercism/stream_exercise_test.rb [hunk 5]
```diff
@@ -0,0 +1,52 @@
...
+  def test_at
+    date = '2016-08-01'
+    args = [:id, :uuid, :problem, :last_activity, date, :iteration_count, :last_activity_at, :help_requested, :avatar_url]
+    exercise = Stream::Exercise.new(*args)
+    expected = date.to_datetime
+    assert_equal expected, exercise.at
+  end
+
+  # It's not possible to construct a viewed exercise.
+  def test_viewed!
```
Comment (kytrinyx) [inline test/exercism/stream_exercise_test.rb]: I don't feel any compelling need to have a test for every single method. The behavior is adequately tested below, and would delete this test.

File: test/exercism/stream_exercise_test.rb (hunk 3 above)
Comment (kytrinyx) [inline test/exercism/stream_exercise_test.rb]: Oh, do you mean that it's not possible to create an Exercise that is viewed without calling `viewed!`?

**Comment by kytrinyx** [comment]
The comments are minor. I want to get this fix in quickly, and we can discuss the details in a second PR.

Thanks so much, @Insti.

**Comment by Insti** [comment]
Yeah I need to clean up that file. The comments are mostly left over from working out what everything was supposed to be doing.
I'll submit another PR with a cleaned up version.

Philosophy: 
I think it's important to have tests for every public method of a class. 
When a test is empty/unnecessary/redundant that's usually an indication that the class under test could do with some refactoring.

**Comment by kytrinyx** [comment]
> When a test is empty/unnecessary/redundant that's usually an indication that the class under test could do with some refactoring.

Agreed... that said I am pretty sure all of Exercism could do with refactoring. I have a bunch of ideas about that, but am pretty snowed under and it hasn't migrated to the top of my list yet :/
