### PR TITLE
[FIXES #2716]decrements iteration count of submissions user_exercise

### LINKED ISSUE #2716: Deleting all iterations from a solution doesn't remove it from the dashboard.
Reproduction steps:

- submit a solution to an exercise
- delete the solution manually via the web interface
- go to the dashboard

=> It will still be listed in the "you're working on" list.

### PR DESCRIPTION
**Pull request by AlexWheeler**
fixes issue #2716
The issue is that the dashboard queries user_exercises using the 'current' scope.  This scope looks for user_exercises where iteration_count > 0.  However the submissions delete route wasn't decrementing the submission.user_exercise iteration_count so although the submission was deleted the user_exercise would still be returned in the query.

Only spec I'm having trouble with is the request spec, have it working in browser but can't seem to get submission.user_exercise to update in the spec.  Am I supposed to be using the Hack::UpdatesUserExercise as in the other tests in test/submission_test.rb

### CODE REVIEW

**Comment by AlexWheeler** [comment]
not to familiar with Travis CI, but Github integration says the build failed, yet when I go to Travis it says 0 errors.  Am I missing something?

**Comment by kytrinyx** [comment]
Good find! Yeah, I think it's easiest to use `Hack::UpdatesUserExercise`. If that doesn't work, let me know and I'll take a look.

The tests passed, but there's some trailing whitespace somewhere:

```plain
The command "! git grep ' $' -- \*.rb" exited with 1.
```

**Comment by AlexWheeler** [comment]
sweet thanks for heads up. Let me know what you think of PR

File: lib/exercism/user_exercise.rb [hunk 1]
```diff
@@ -66,6 +66,11 @@ def comment_count
     @comment_count ||= Hash(ActiveRecord::Base.connection.execute(comment_count_sql).to_a.first)["total"].to_i
   end
 
+  def decrement_iteration_count!
+    new_iteration_count = self.iteration_count - 1
+    update_attributes(iteration_count: new_iteration_count)
```
Comment (kytrinyx) [inline lib/exercism/user_exercise.rb]: Let's inline this--no reason to assign a temporary variable.

File: app/routes/submissions.rb [hunk 2]
```diff
@@ -62,6 +62,7 @@ class Submissions < Core
         end
 
         decrement_version(submission)
+        decrement_exercise_iteration_count(submission)
```
Comment (kytrinyx) [inline app/routes/submissions.rb]: Let's just call `submission.user_exercise.decrement_iteration_count!` directly here.

**Comment by kytrinyx** [comment]
Thanks Alex, I had a couple of small comments.

**Comment by AlexWheeler** [comment]
sweet thanks, great comments.

**Comment by kytrinyx** [comment]
:tada: Thanks!
