### PR TITLE
Fix aggregated unread submission count in Team stream.

### LINKED ISSUE #2946: Teams activity stream does show far too many unread submissions
In my team I do have an overall unread count of nearly 600 items, while there are only about 100 items unread over the languages.

exercism-team-view

### PR DESCRIPTION
**Pull request by bernardoamc**
Fixes #2946 

Turns out [this assertion](https://github.com/exercism/exercism.io/blob/master/test/exercism/team_stream_filters_test.rb#L40) was failing in my local environment.

### CODE REVIEW

File: lib/exercism/team_stream_filters.rb [hunk 1]
```diff
@@ -72,7 +72,7 @@ def sql
     # rubocop:disable Metrics/MethodLength
     def views_sql
       <<-SQL
-      SELECT 1 AS id, COUNT(views.id) AS total
+      SELECT '#{team_slug}' AS id, COUNT(1) AS total
```
Comment (bernardoamc) [inline lib/exercism/team_stream_filters.rb]: Thinking if this can be dangerous... Maybe not since this code is only executed if the team is valid, but still...

Comment (kytrinyx) [inline lib/exercism/team_stream_filters.rb]: Good point. I think we should use the team_id if we can. Do we have it? If not, do we have the entire team at an earlier point so we could make the id available?

Comment (bernardoamc) [inline lib/exercism/team_stream_filters.rb]: This is probably the best course of action, I will investigate this and make the necessary changes.

File: lib/exercism/team_stream_filters.rb [hunk 2]
```diff
@@ -72,7 +72,7 @@ def sql
     # rubocop:disable Metrics/MethodLength
     def views_sql
       <<-SQL
-      SELECT 1 AS id, COUNT(views.id) AS total
+      SELECT 'team_stream' AS id, COUNT(1) AS total
```
Comment (bernardoamc) [inline lib/exercism/team_stream_filters.rb]: @kytrinyx I think we can just hardcode the `id` for an aggregated submission count since the stream name is not important for the query. What do you think?

Comment (kytrinyx) [inline lib/exercism/team_stream_filters.rb]: Yeah, that sounds like a great approach. We definitely don't need the stream name.

Comment (kytrinyx) [inline lib/exercism/team_stream_filters.rb]: Wait. I think maybe I don't understand.

Why do we need an `id` at all? What are we using it for?

Comment (kytrinyx) [inline lib/exercism/team_stream_filters.rb]: OK, so you're saying that we're only going to have one row, and therefore the id can be whatever we want it to be. We don't use the id to display anything, and we're not grouping on anything.

**Comment by kytrinyx** [comment]
I think this is ready to merge. Is there anything else you want to do before I merge it?

File: lib/exercism/team_stream_filters.rb (hunk 2 above)
Comment (bernardoamc) [inline lib/exercism/team_stream_filters.rb]: Exactly! It is only needed in [this](https://github.com/exercism/exercism.io/blob/master/lib/exercism/track_stream_filters.rb#L10) step.

**Comment by bernardoamc** [comment]
I don't think so, let's give it a try. :)

**Comment by kytrinyx** [comment]
Thanks :)
