### PR TITLE
Fix for double posting comments with ⌘+Enter

### LINKED ISSUE #2221: ⌘+Enter double submits comment (doesn't disable 'submit' button)
I seem to have this problem more often when I comment on my own exercism than I've commenting on other users exercisms.

image

Manually deleting the duplicate will remove the duplicate and leave the extra.

image

### PR DESCRIPTION
**Pull request by trayo**
Fixes the issue where the submit button isn’t disabled when the user submits a nit using `cmd/ctrl + enter` the submit button will be disabled.

It also fixes the user being able to send `cmd/ctrl + enter` multiple times which would send multiple comments with the same body.

I only changed the Javascript under `lib/app/public` and not under `/frontend`. Should I add it there as well or is `/frontend` only for style development?

closes #2221

### CODE REVIEW

File: lib/app/public/js/app.js [hunk 1]
```diff
@@ -30180,11 +30180,17 @@ $(function() {
...
+    var $this = $(this).find('button');
     window.setTimeout(function() { $this.attr('disabled', true); }, 1);
   });
 
+  $("form").submit(function() {
+    $(this).submit(function() {
+      return false;
+    });
+  });
+
```
Comment (trayo) [inline lib/app/public/js/app.js]: This function prevents the user from sending ⌘+Enter multiple times.

**Comment by kytrinyx** [comment]
Yeah, it should all be done in `frontend/` otherwise it will get lost when we regenerate the public stuff. It's a right mess at the moment, I apologize for that. For a while I had it auto-generating on deploy, but there was a screwup with dependencies, and I haven't gotten it fixed.

**Comment by trayo** [comment]
It's no problem. :grinning: 

Does that mean I should duplicate the code to `/frontend` or remove it from `lib/app/public/` and move it to `/frontend`? When I originally put it in `/frontend` it wasn't working for development.

**Comment by trayo** [comment]
I'm having trouble finding where the javascript is being generated from. I found it in `/frontend/generated` but that's in the gitignore and seems to be generated from an external source.

**Comment by kytrinyx** [comment]
@trayo This is so embarrassing, I can't remember how this works! @fluxusfrequency Do you recall how you figured it out?

The right answer might be to just leave it where it is.

**Comment by fluxusfrequency** [comment]
Not sure if this is where the code you're looking for lives, but this is where it comes from: https://github.com/exercism/exercism.io/tree/master/frontend/app/js. Read the README in /frontend for info on how to build and test.

**Comment by kytrinyx** [comment]
Ah, yes. Thank you!

**Comment by trayo** [comment]
Thanks @fluxusfrequency and @kytrinyx for the help! I believe I got duplicated to the front end correctly. I ran lineman and it passed and compiled.

File: frontend/app/js/script.js [hunk 2]
```diff
@@ -29,11 +29,18 @@ $(function() {
     $("a[data-action='enlarge']",codeDiv).show();
   });
 
-  $('form input[type=submit], form button[type=submit]').on('click', function() {
-    var $this = $(this);
+  $('form').on('submit', function() {
+    var $this = $(this).find('button');
```
Comment (fluxusfrequency) [inline frontend/app/js/script.js]: This no longer catches `input[type="submit"]`. Don't know if there are any. Maybe it's just buttons.

Comment (trayo) [inline frontend/app/js/script.js]: It seems what the function was doing was finding the button that's related to the form and disabling it on click. With form on submit, it will find the related button and disable much in the same way, but with the purpose of disabling it if you click on it or send the form with ⌘+Enter.

Comment (fluxusfrequency) [inline frontend/app/js/script.js]: I get what it's doing, my point is that the old implementation was catching the event on both `button` and `input[type="submit"]` elements, but now it doesn't catch the latter. I would use `ack` to find any forms and make sure that there aren't any that are using `<input type="submit">` instead of `<button>`. Or just find both on line 33 here.

Comment (trayo) [inline frontend/app/js/script.js]: Ah! I see what you mean. I think I found a solution and will push it shortly. I want to click around some more to test it. Thanks!

**Comment by trayo** [comment]
@fluxusfrequency I seem to have success with finding the `:submit` of the form that's given to the function. What do you think?

**Comment by fluxusfrequency** [comment]
Does it find the button and input type="submit"s?

I probably would have done
```
var $this = $(this).find('button, input[type="submit"]');
```

Also is there a reason you're doing a `setTimeout` with 1 millisecond? Do you know about `setTimeout` with 0? It waits until the current item on the callstack has completed before executing the code. Not sure why you would even need a timeout here, but maybe you do.

**Comment by fluxusfrequency** [comment]
Also, instead of doing `$this = $(this)`, you can just call `}.bind(this)` on the end of the function FWIW.

**Comment by trayo** [comment]
I tested it in console and it does indeed find the `input` and `button` where type=submit.

The setTimeout was already there in the function and I wasn't sure if it was needed, so I left it. Would you prefer I change it while I'm there?

Same for `$this = $(this)`. I can change that as well and do some refactoring.

**Comment by fluxusfrequency** [comment]
Nah I think you're good.

**Comment by trayo** [comment]
Thanks @fluxusfrequency!
