### PR TITLE
Fix viewer filter pagination

### LINKED ISSUE #3133: Viewer filter in track stream paginates incorrectly
We recently added a "my solutions" filter to the sidebar of the track activity stream (#3115). This makes it quick and easy to go see all of your own exercises, and quickly navigate to the ones where there has been new activity (comments) since you last looked at it.

In my own solutions for the Go track I should not have any pagination, since I have only submitted to exercises. I would expect someone who has submitted over 50 exercises in a single track (e.g. @ErikSchierboom or @NobbZ) to have 2 pages.

-------

screen shot 2016-10-02 at 1 50 51 am

/cc @ramyaravindranath

### PR DESCRIPTION
**Pull request by bernardoamc**
Fixes #3133

This PR solves the pagination problem referenced in #3133 , the problem is currently happening because we only consider as active a problem stream or track stream filters, not the viewer filter. When we are in `My Solutions` we should consider the Viewer filter as active and paginate using its result.

### CODE REVIEW

File: test/exercism/track_stream_test.rb [hunk 1]
```diff
@@ -204,6 +204,10 @@ def test_mark_as_read
     assert_equal expected, actual
   end
 
+  def test_paginate_by_active_menu_item
```
Comment (bernardoamc) [inline test/exercism/track_stream_test.rb]: Going to work on this probably tomorrow.

**Comment by kytrinyx** [comment]
Ahh, nice find!

**Comment by bernardoamc** [comment]
Finally had some time to finish this, crazy week!

**Comment by kytrinyx** [comment]
> crazy week!

Me too. Every day I kept thinking "I will go look at all the open PRs". And then suddenly it was midnight and I hadn't.
